export const dados = [
    {
        "id": 1,
        "img": "https://images.contentstack.io/v3/assets/bltb6530b271fddd0b1/blt1fb651358bfe01fe/60c10342d475801b9d54fe31/TORNEIOS_DE_COMUNIDADE_VAL_CARD.jpg",
        "title": "Nova atualização valorant",
        "content": "O VALORANT exige que você tome decisões difíceis ao interagir com os utilitários inimigos: disparar, esquivar e calcular o momento certo para realizar uma ação decisiva. Queremos que todo mundo termine as rodadas sentindo que poderia ter feito uma jogada melhor com um pouco mais de agilidade ou esperteza. A equipe percebeu que, ao enfrentar vários utilitários ou algumas das ultimates mais impactantes, as chances de contrajogada podem ficar sobrecarregadas, fazendo com que você não tenha certeza do que está acontecendo ou do que poderia fazer de diferente da próxima vez. A Atualização 7.04 inclui mudanças para mais da metade do elenco, mas o principal foco é aumentar a clareza do estado de jogo com os seguintes ajustes: Reduzir a frequência de ultimates com grande área de ação. Reduzir a quantidade de tempo que um utilitário fica ativo no ambiente. Reduzir a Vida de utilitários que podem levar tiros. Também acreditamos que as atualizações de custos abaixo alinham melhor as ultimates de alto impacto e grande área com a pressão que causam nos inimigos, criando tanto um ritmo melhor para as habilidades que definem rodadas quanto uma competição mais clara entre ultimates de alto custo e de baixo custo."
    },

    {
        "id": 2,
        "img": "https://tm.ibxk.com.br/2023/09/21/21160050301251.jpg?ims=1120x420",
        "title": "Microsoft anuncia novos recursos de IA para o Bing e o Edge; veja",
        "content": "A Microsoft apresentou nesta quinta-feira (21) novos recursos para o Bing e o Edge, que serão atualizados com os modelos de inteligência artificial (IA) mais recentes da companhia. As respostas personalizadas, baseadas no histórico de bate-papo com a ferramenta inteligente, estão entre as novidades. Caso o usuário tenha ido ao Bing Chat pesquisar sobre um time de futebol, por exemplo, o chatbot poderá informar, na próxima vez, se a equipe irá jogar em uma cidade sobre a qual você está buscando informações. Quem utiliza o Microsoft Shopping no Edge ou por meio dos resultados no Bing também irá notar algumas diferenças, graças à introdução do Copilot na plataforma. A IA da gigante de Redmond ajudará a encontrar os melhores preços para determinados produtos e trará recomendações baseadas nas suas preferências, além de permitir pesquisas por meio de fotos. Já o recém-lançado Bing Chat Enterprise, que acumula mais de 160 milhões de usuários em dois meses, ficará disponível também no app móvel do Microsoft Edge. A plataforma ganhou ainda o suporte multimodal, permitindo usar textos e imagens nas interações com o usuário." 
    },
    {
        "id":3,
        "img":"https://s2-ge.glbimg.com/HaIhNNruUHdjiKy0aNhSioxMeSo=/0x0:677x381/984x0/smart/filters:strip_icc()/i.s3.glbimg.com/v1/AUTH_bc8228b6673f488aa253bbcb03c80ec5/internal_photos/bs/2022/e/p/B0enCqQyKXWynD2fTIRg/chamber-valorant.jpg",
        "title":"Entenda a taxa baixa de pick do chamber no competitivo",
        "content": "A Riot Games anunciou, nesta terça-feira, o patch notes completo da atualização 3.10 do Valorant. Entre as novidades mais esperadas pelo público está a chegada do novo agente, Chamber. Além disso, os jogadores poderão criar grupos com cinco integrantes para todos os ranques da fila competitiva, mas contarão com algumas condições que vão impactar a quantidade de pontos de classificação adquirida pelo grupo. Após sua revelação completa, o sentinela Chamber chega oficialmente aos servidores do Valorant. No dia 12 de novembro, os jogadores do servidor de testes tiveram a chance de jogar com o agente; agora, o sentinela está disponível para ser desbloqueado por todos os jogadores. Veja as habilidades: Trademark (C): Coloca uma armadilha que procura pelos inimigos. Quando um inimigo visível chega ao alcance, a armadilha faz uma contagem regressiva e desestabiliza o terreno ao redor, no qual diminui a velocidade deles. Headhunter (Q): Ativa para equipar uma pistola pesada que contém uma mira exclusiva da arma. Rendezvous (E): O agente coloca duas âncoras de teletransporte. Enquanto estiver no chão e ao alcance da âncora, o usuário poderá reativar para se teletransportar para a outra âncora. As âncoras podem ser recuperadas e depositadas em outros lugares do mapa. Tour de Force (X): A ultimate ativar um rifle de precisão que matará um inimigo com qualquer ataque direto. Abater o adversário irá criar um campo persistente que diminui a velocidade dos jogadores." 
    },
    {
        "id": 4,
        "img":"https://conteudo.imguol.com.br/c/entretenimento/11/2021/05/19/valorant-breeze-1621432260666_v2_900x506.png",
        "title":"Mapa breeze, agora na nova atualização, tem diversas mudanças, Confira!",
        "content": "A Riot Games anunciou, nesta terça-feira, o patch notes completo da atualização 3.10 do Valorant. Entre as novidades mais esperadas pelo público está a chegada do novo agente, Chamber. Além disso, os jogadores poderão criar grupos com cinco integrantes para todos os ranques da fila competitiva, mas contarão com algumas condições que vão impactar a quantidade de pontos de classificação adquirida pelo grupo. Após sua revelação completa, o sentinela Chamber chega oficialmente aos servidores do Valorant. No dia 12 de novembro, os jogadores do servidor de testes tiveram a chance de jogar com o agente; agora, o sentinela está disponível para ser desbloqueado por todos os jogadores. Veja as habilidades: Trademark (C): Coloca uma armadilha que procura pelos inimigos. Quando um inimigo visível chega ao alcance, a armadilha faz uma contagem regressiva e desestabiliza o terreno ao redor, no qual diminui a velocidade deles. Headhunter (Q): Ativa para equipar uma pistola pesada que contém uma mira exclusiva da arma. Rendezvous (E): O agente coloca duas âncoras de teletransporte. Enquanto estiver no chão e ao alcance da âncora, o usuário poderá reativar para se teletransportar para a outra âncora. As âncoras podem ser recuperadas e depositadas em outros lugares do mapa. Tour de Force (X): A ultimate ativar um rifle de precisão que matará um inimigo com qualquer ataque direto. Abater o adversário irá criar um campo persistente que diminui a velocidade dos jogadores." 
    }

]